#!/usr/bin/env bash
# Script to transfer a file from client to a server
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]
then
	scp -o StrickHostKeyChecking=no "$1" "$3@$2:~/"
else
	scp -o StrickHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
