#!/usr/bin/env bash
#Script to install Nginx on a server
sudo apt-get -y update
sudo apt-get -y install nginx

#starting Nginx service
sudo service nginx start

#allowing nginx on firewalls
sudo ufw allow 'Nginx HTTP'

#change ownership to user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

#setting /redirect_me
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#setting HTTP 404 error code
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

#Restarting nginx
sudo service nginx restart
