#!/usr/bin/env bash
#script to manage my process
. /lib/lsb/init-functions

pros_file=/var/run/my_process.pid

start() {
	./manage_my_process &
	echo "$!" > "$pros_file"
}

stop() {
	sudo kill -15 "$(cat "$pros_file")" && rm -rf "$pros_file"
}

case "$1" in
	start)
		start
		echo "manage_my_process statrted"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
