#!/usr/bin/env bash
#script to manage my process
#./lib/lsb/init-functions

PROS_FILE=/var/run/my_process.pid

$PROS_FILE

start() {
	./manage_my_process &
	echo "$!" > "$PROS_FILE"
}

stop() {
	sudo kill -15 "$(cat "$PROS_FILE")" && rm -f "$PROS_FILE"
}

case "$1" in
	start)
		start
		echo "manage_my_process statrted"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
