#!/usr/bin/env bash
#Display number and FizzBuzz
for i in {1..100}
do
	a=$(( i % 3 ))
	b=$(( i % 5 ))
	if [ $a = 0 ] && [ $b = 0 ]
	then
		echo "FizzBuzz"
	elif [ $a = 0 ]
	then
		echo "Fizz"
	elif [ $b = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
