#!/usr/bin/env bash
#script to tell the story of passwd
while IFS= read -r line
do
	USERNAME=$(echo "$line" | cut -f 1 -d ':')
	GROUPID=$(echo "$line" | cut -f 4 -d ':')
	home=$(echo "$line" | cut -f 6 -d ':')
	COMMAND=$(echo "$line" | cut -f 7 -d ':')
	USERID=$(echo "$line" | cut -f 3 -d ':')
	PASSWORD=$(echo "$line" | cut -f 2 -d ':')
	USERINFO=$(echo "$line" | cut -f 5 -d ':')

	echo "The user $USERNAME is part of the $GROUPID gang, lives in $home and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERINFO"

done < "/etc/passwd"
