#!/usr/bin/env bash
#script to give information about script
list='ls'
for _ in $list
do
	if [ -e "school" ]
	then
		echo "school file exists"
		if [ -s "school" ]
		then
			echo "school is not empty"
		else
			echo "school is empty"
		fi
		if [ -f "school" ]
		then
			echo "school is a regular file"
		fi
	else
		echo "shool file does not exist"
	fi
done
